/* AUTO-GENERATED by encrypt.mjs — public countdown info only (no itinerary). */
window.TRIP_CONFIG = {"title":"California Road Trip","subtitle":"July 16 – 26, 2026 · Family of Five","startDate":"2026-07-16","endDate":"2026-07-26"};
