/* ============================================================================
   encrypt.mjs — turn secrets.plain.json into the deployable data.enc.js
   ----------------------------------------------------------------------------
   Usage:
       node encrypt.mjs <passcode>
   e.g. node encrypt.mjs california2026

   • Reads the plaintext confirmation numbers from secrets.plain.json
   • Encrypts them with your passcode (AES-256-GCM, key stretched with PBKDF2)
   • Writes data.enc.js — the ONLY secrets file that gets deployed (it's ciphertext)

   To change the passcode: just run this again with the new passcode, then redeploy.
   The website will ask family members for whatever passcode you used here.

   Never deploy secrets.plain.json or this file (see .vercelignore / .gitignore).
   ========================================================================== */

import { readFile, writeFile } from "node:fs/promises";
import { webcrypto as crypto } from "node:crypto";

const ITERATIONS = 150000;

const passcode = process.argv[2] || process.env.TRIP_PASSCODE;
if (!passcode) {
  console.error("\n  Missing passcode.\n  Usage: node encrypt.mjs <passcode>\n");
  process.exit(1);
}

const enc = new TextEncoder();
const b64 = (buf) => Buffer.from(buf).toString("base64");

async function deriveKey(pass, salt) {
  const baseKey = await crypto.subtle.importKey("raw", enc.encode(pass), "PBKDF2", false, ["deriveKey"]);
  return crypto.subtle.deriveKey(
    { name: "PBKDF2", salt, iterations: ITERATIONS, hash: "SHA-256" },
    baseKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt"]
  );
}

const plain = await readFile(new URL("./secrets.plain.json", import.meta.url), "utf8");
const parsed = JSON.parse(plain);
delete parsed._README; // don't ship the helper note

const salt = crypto.getRandomValues(new Uint8Array(16));
const iv = crypto.getRandomValues(new Uint8Array(12));
const key = await deriveKey(passcode, salt);
const cipher = await crypto.subtle.encrypt(
  { name: "AES-GCM", iv },
  key,
  enc.encode(JSON.stringify(parsed))
);

const payload = {
  v: 1,
  iter: ITERATIONS,
  salt: b64(salt),
  iv: b64(iv),
  data: b64(cipher),
};

const out =
  "/* AUTO-GENERATED by encrypt.mjs — do not edit by hand.\n" +
  "   This is the ENCRYPTED confirmation numbers. Safe to deploy publicly:\n" +
  "   it cannot be read without the passcode. To change it, edit\n" +
  "   secrets.plain.json and re-run: node encrypt.mjs <passcode> */\n" +
  "window.TRIP_SECRETS_ENC = " + JSON.stringify(payload) + ";\n";

await writeFile(new URL("./data.enc.js", import.meta.url), out, "utf8");
console.log("\n  ✓ Wrote data.enc.js (encrypted). Passcode set to: " + passcode + "\n");
