/* ============================================================================
   encrypt.mjs — bundle the private trip data into the deployable site files
   ----------------------------------------------------------------------------
   Usage:
       node encrypt.mjs <passcode>
   e.g. node encrypt.mjs california2026

   Reads:   data.js            (the full itinerary — schedule, food, links, tips)
            secrets.plain.json (confirmation numbers)
   Writes:  data.enc.js        ← the ENTIRE itinerary, encrypted (safe to deploy)
            config.js          ← just the trip name + dates, for the public
                                  countdown screen (safe to deploy, not sensitive)

   Everything in data.js + secrets.plain.json is encrypted together with your
   passcode (AES-256-GCM, key stretched with PBKDF2). Nothing readable ships
   except the countdown title/dates in config.js.

   To change the passcode: run this again with the new one, then redeploy.
   Never deploy data.js, secrets.plain.json, or this file (see .vercelignore).
   ========================================================================== */

import { readFile, writeFile } from "node:fs/promises";
import { webcrypto as crypto } from "node:crypto";

const ITERATIONS = 150000;

const passcode = process.argv[2] || process.env.TRIP_PASSCODE;
if (!passcode) {
  console.error("\n  Missing passcode.\n  Usage: node encrypt.mjs <passcode>\n");
  process.exit(1);
}

const enc = new TextEncoder();
const b64 = (buf) => Buffer.from(buf).toString("base64");

async function deriveKey(pass, salt) {
  const baseKey = await crypto.subtle.importKey("raw", enc.encode(pass), "PBKDF2", false, ["deriveKey"]);
  return crypto.subtle.deriveKey(
    { name: "PBKDF2", salt, iterations: ITERATIONS, hash: "SHA-256" },
    baseKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt"]
  );
}

// --- load the private sources -------------------------------------------------
const { default: TRIP } = await import("./data.js");

const secretsRaw = await readFile(new URL("./secrets.plain.json", import.meta.url), "utf8");
const secrets = JSON.parse(secretsRaw);
delete secrets._README;

// --- encrypt the whole thing --------------------------------------------------
const payload = { trip: TRIP, secrets };

const salt = crypto.getRandomValues(new Uint8Array(16));
const iv = crypto.getRandomValues(new Uint8Array(12));
const key = await deriveKey(passcode, salt);
const cipher = await crypto.subtle.encrypt(
  { name: "AES-GCM", iv },
  key,
  enc.encode(JSON.stringify(payload))
);

const encPayload = { v: 1, iter: ITERATIONS, salt: b64(salt), iv: b64(iv), data: b64(cipher) };

await writeFile(
  new URL("./data.enc.js", import.meta.url),
  "/* AUTO-GENERATED by encrypt.mjs — do not edit by hand.\n" +
  "   The ENTIRE itinerary, encrypted. Safe to deploy: unreadable without the\n" +
  "   passcode. To change it, edit data.js / secrets.plain.json and re-run:\n" +
  "   node encrypt.mjs <passcode> */\n" +
  "window.TRIP_SECRETS_ENC = " + JSON.stringify(encPayload) + ";\n",
  "utf8"
);

// --- public, non-sensitive countdown info ------------------------------------
const config = {
  title: TRIP.title,
  subtitle: TRIP.subtitle,
  startDate: TRIP.startDate,
  endDate: TRIP.endDate,
};
await writeFile(
  new URL("./config.js", import.meta.url),
  "/* AUTO-GENERATED by encrypt.mjs — public countdown info only (no itinerary). */\n" +
  "window.TRIP_CONFIG = " + JSON.stringify(config) + ";\n",
  "utf8"
);

console.log("\n  ✓ Wrote data.enc.js (encrypted) + config.js (public countdown).");
console.log("    Passcode set to: " + passcode + "\n");
